export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as Quotes } from './Quotes'
export { default as Invoices } from './Invoices'
export { default as Profile } from './Profile'
